language: php

php:
- 5.6
- 7.0
- 7.1
- 7.2

services:
- mysql

before_script:
- cp '.env.travis .env'
- mysql -e 'create database test;'
- composer self-update
- composer install --no-interaction

script:
    - vendor/bin/phpunit