language: php

matrix:
  include:
     - php: 7.1
      env: WP_TRAVISCI=travis:phpunit
    - php: 7.2
      env: WP_TRAVISCI=travis:phpunit
    - php: 7.3
      env: WP_TRAVISCI=travis:phpunit
    - php: hhvm
      env: WP_TRAVISCI=travis:phpunit
  allow_failures:
    - php: 7.2
    - php: hhvm
  fast_finish: true
  
services:
  - mysql

env:
  global:

    - DB_HOSTNAME=127.0.0.1
    - DB_DATABASE= test
    - DB_USERNAME=root
    - DB_PASSWORD=
 

before_install:
  - mysql -e 'CREATE DATABASE test;'
