language: php

matrix:
  include:
  - php: 7.2
    env: WP_TRAVISCI=e2e
  - php: 7.2
    env: WP_TRAVISCI=travis:format
  - php: 7.1
    env: WP_TRAVISCI=travis:js
  - php: 7.4snapshot
  - php: 7.3
  - php: 7.3
    env: WP_TRAVIS_OBJECT_CACHE=true
    services: memcached
  - php: 7.2
  - php: 7.1
  - php: 7.0
    env: WP_TEST_REPORTER=true
  - php: 5.6
  - php: nightly
  allow_failures:
  - php: 7.4snapshot
  - php: nightly
  fast_finish: true
  
services:
  - mysql

env:
  global:

    - DB_HOSTNAME=127.0.0.1
    - DB_DATABASE= test
    - DB_USERNAME=root
    - DB_PASSWORD=
 

before_install:
  - mysql -e 'CREATE DATABASE test;'

script: ./civic.sh