
language: php

php:

 - 7.0
 - 7.1
 - 7.2
 - 7.3

before_script:
  - mysql -e 'CREATE DATABASE test;'

services:
 - mysql
 
deploy:
  provider: script
  script: bash scripts/deploy.sh
  on:
    branch: develop
 

notifications:
 email: your_email