language: php

php:
- 7.0
- 7.1
- 7.2

services:
- mysql

before_script:
- mysql -e 'create database test;'
- composer self-update
- composer install --no-interaction
- cp .env.travis .env


script:
    - vendor/bin/phpunit