language: php

php:
  - '7.1'
  env : WP_TRAVISCI = travis: phpunit
  - '7.2'
  env : WP_TRAVISCI = travis: phpunit 
  - '7.3'
  env : WP_TRAVISCI = travis: phpunit  
  
services:
  - mysql

env:
  global:

    - DB_HOSTNAME=127.0.0.1
    - DB_DATABASE= test
    - DB_USERNAME=root
    - DB_PASSWORD=
 

before_install:
  - mysql -e 'CREATE DATABASE test;'
