language: php

matrix:
  include:
  - php: 7.1
      dist: precise
  - php: 7.2
      dist: precise
  - php: 7.3
      dist: precise
  
services:
  - mysql

env:
  global:

    - DB_HOSTNAME=127.0.0.1
    - DB_DATABASE= test
    - DB_USERNAME=root
    - DB_PASSWORD=
 

before_install:
  - mysql -e 'CREATE DATABASE test;'

script: ./civic.sh