language: php

php:
  - 7.0
  - 7.1
  - 7.2

matrix:
  include:
    - php: 5.3
      dist: precise

sudo: false

before_script:
  - mysql -e 'CREATE DATABASE test;'

services:
 - mysql
 
before_script: composer install

script: 'Se realizo'
         

 