
language: php

php:

 - 7.0
 - 7.1
 - 7.2
 - 7.3

before_script:
  - mysql -e 'CREATE DATABASE test;'

services:
 - mysql
 
script:
  script: bash scripts/deploy.sh
 

notifications:
 email: your_email